<?xml version="1.0" encoding="UTF-8"?><testsuite name="nosetests" tests="4" errors="1" failures="1" skip="1"><testcase classname="test_skip" name="test_ok" time="0" /><testcase classname="test_skip" name="test_err" time="0"><error type="exceptions.Exception" message="oh no"><![CDATA[Traceback (most recent call last):
  File "/home/jpellerin/jython2.5.2rc1/Lib/unittest.py", line 260, in run
    testMethod()
  File "/tmp/nose_release_1.0.0/nose/case.py", line 187, in runTest
    self.test(*self.arg)
  File "/tmp/nose_release_1.0.0/functional_tests/doc_tests/test_xunit_plugin/support/test_skip.py", line 7, in test_err
    raise Exception("oh no")
Exception: oh no
]]></error></testcase><testcase classname="test_skip" name="test_fail" time="0"><failure type="exceptions.AssertionError" message="bye"><![CDATA[Traceback (most recent call last):
  File "/home/jpellerin/jython2.5.2rc1/Lib/unittest.py", line 260, in run
    testMethod()
  File "/tmp/nose_release_1.0.0/nose/case.py", line 187, in runTest
    self.test(*self.arg)
  File "/tmp/nose_release_1.0.0/functional_tests/doc_tests/test_xunit_plugin/support/test_skip.py", line 10, in test_fail
    assert False, "bye"
AssertionError: bye
]]></failure></testcase><testcase classname="test_skip" name="test_skip" time="0"><skipped type="nose.plugins.skip.SkipTest" message="not me"><![CDATA[Traceback (most recent call last):
  File "/home/jpellerin/jython2.5.2rc1/Lib/unittest.py", line 260, in run
    testMethod()
  File "/tmp/nose_release_1.0.0/nose/case.py", line 187, in runTest
    self.test(*self.arg)
  File "/tmp/nose_release_1.0.0/functional_tests/doc_tests/test_xunit_plugin/support/test_skip.py", line 13, in test_skip
    raise SkipTest("not me")
SkipTest: not me
]]></skipped></testcase></testsuite>